// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvjeUi7HyHrp61wFvLzVQcOdo8vggaD10',
    appId: '1:65782964291:web:f1cfb1a5a118fd013534f6',
    messagingSenderId: '65782964291',
    projectId: 'learneasy-d535a',
    authDomain: 'learneasy-d535a.firebaseapp.com',
    storageBucket: 'learneasy-d535a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3RuqUjUMuw4BLrsGAqm4ZVq8GIVQEYLk',
    appId: '1:65782964291:android:a02dcbb4d94c0a283534f6',
    messagingSenderId: '65782964291',
    projectId: 'learneasy-d535a',
    storageBucket: 'learneasy-d535a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZOQVxPrF_Qw3JSFQfv1cpuM48-WA3d9A',
    appId: '1:65782964291:ios:8a8ea1b834b737c73534f6',
    messagingSenderId: '65782964291',
    projectId: 'learneasy-d535a',
    storageBucket: 'learneasy-d535a.firebasestorage.app',
    iosBundleId: 'com.example.learneasy',
  );
}
